services:
  db:
    image: "postgres:12"
    container_name: "db_hackatop"
    ports:
      - "54320:5432"
    volumes:
      - db_hackatop:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_hackatop
      POSTGRES_USER: usr_hackatop
      POSTGRES_PASSWORD: usr_hackatop
volumes:
  db_hackatop:
